### ISSUE TITLE
Visual Studio 2017 (vc141) にてコンパイルエラー

### ISSUE THREAD

**Issue by matsudai** [bolero-MURAKAMI/Sprout#86]
https://github.com/bolero-MURAKAMI/Sprout/blob/master/sprout/type_traits/result_of.hpp

Visual Studio 2015 (vc140) ではコンパイルが通っていたのですが
Visual Studio 2017 (vc141) ではコンパイルエラーとなりました

原因はvcの以下の仕様変更でした
* テンプレート引数にパラメータパックが含まれている場合，それはパラメータリストの最後になければならない
* テンプレートにネストされた依存名はtypenameにより明示されなければならない

とりあえず現在は`if defined(_MSC_VER) && (_MSC_VER <= 1900)` ブロックをコメントアウトして対応しています（このときvc140，vc141共にコンパイルが通りました）

**Comment by bolero-MURAKAMI** [comment]
Try it.
74d7368aa5bf099e43ba8476c345ee37ba5bc56a

**Comment by matsudai** [comment]
Thank you for your work!
I close this Issue.
