### ISSUE TITLE
Getting Sprout Version

### ISSUE THREAD

**Issue by adishavit** [bolero-MURAKAMI/Sprout#88]
Does Sprout have a version macro that can be used to find it's version number/string?

**Comment by bolero-MURAKAMI** [comment]
There have been no version numbers in Sprout so far.
I have no idea of proper version notation.

As a temporary correspondence, added a macro to acquire the commit date in yyyyMMdd format.
It is not the best, but I think it will be useful.

in header sprout/version.hpp
macro SPROUT_VERSION_YYYYMMDD
6de283cf1ca12b44b46518aceca64fdbc5506c80

**Comment by bolero-MURAKAMI** [comment]
Include version.hpp from config.hpp.
If you want to check the version assuming previous revisions without version.hpp, include config.hpp and check for macros.
759265d6245e2a567d88c6050ec0a5ce6d256f17

**Comment by adishavit** [comment]
Thanks!
