### ISSUE TITLE
Sprout on Wandbox seem broken

### ISSUE THREAD

**Issue by adishavit** [bolero-MURAKAMI/Sprout#89]
See [here](https://wandbox.org/permlink/XjSi9pyCBB4vYFqY).

**Comment by bolero-MURAKAMI** [comment]
Apparently, there seems to be a problem with GCC 7.x or later.
I will investigate.

**Comment by bolero-MURAKAMI** [comment]
It probably seems to be related to template aliases.
Defining SPROUT_CONFIG_DISABLE_TEMPLATE_ALIASES before any headers are included will not result in an error.
https://wandbox.org/permlink/TCBFgUacEArs2ISb

But this is not a fundamental solution, so I think about workaround.

**Comment by bolero-MURAKAMI** [comment]
Workaround was added.
try it.
a79ee37535f5c10bad1ce4e049dd27fd9db2738f

**Comment by adishavit** [comment]
Great!
Thanks!
